source 'https://rubygems.org'
gem 'rails', '4.0.3'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'bootstrap-sass'
gem 'devise'
gem 'figaro'
gem 'haml-rails'
gem 'sendgrid'
gem 'simple_form'
gem 'therubyracer', :platform=>:ruby
gem 'thin'
gem 'impressionist'
gem 'will_paginate', '~> 3.0'
gem "paperclip", "~> 4.1"
gem "paperclip-dropbox", ">= 1.1.7"
gem 'acts-as-taggable-on'
gem 'binding_of_caller'
gem 'jquery-fileupload-rails'
group :development do
  gem 'better_errors'
  gem 'html2haml'
  gem 'quiet_assets'
  gem 'rails_layout'
end
